name: My First Workflow

on: 
  push:
    branches:
      - main  # This ensures the workflow runs on pushes to the main branch. Adjust as needed.

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # This step checks out the repository's code
        
      - name: Welcome Message
        run: echo "My first job"
        
      - name: List Files
        run: ls
        
      - name: Read README.md
        run: cat README.md
